FROM node:lts-alpine3.20

RUN apk add --no-cache \
      bash \
      curl \
      git \
      kitty-terminfo \
      the_silver_searcher

EXPOSE 5000

RUN mkdir /home/node/dev \
 && npm install -g npm@10.8.1

COPY . /home/node/dev

RUN chown -R node: /home/node
WORKDIR /home/node/dev/apps/web
USER node

RUN cd /home/node/dev/apps/web && \
    npm install  && \
    npm run build

CMD ["node_modules/.bin/sirv", "public", "--single", "--dev", "--host"]
